// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain;

[Table("COM_CUSTOMER")]
public partial class ComCustomer
{
    [Key]
    [Column("COM_CUSTOMER_ID")]
    public int ComCustomerId { get; set; }

    [Column("CUSTOMER_NAME")]
    [StringLength(100)]
    [Unicode(false)]
    public string CustomerName { get; set; }
}