// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain;

[Table("SO_ITEM")]
public partial class SoItem
{
    [Key]
    [Column("SO_ITEM_ID")]
    public long SoItemId { get; set; }

    [Column("SO_ORDER_ID")]
    public long SoOrderId { get; set; }

    [Required]
    [Column("ITEM_NAME")]
    [StringLength(100)]
    [Unicode(false)]
    public string ItemName { get; set; }

    [Column("QUANTITY")]
    public int Quantity { get; set; }

    [Column("PRICE")]
    public double Price { get; set; }
}