// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace App.Domain;

[Table("SO_ORDER")]
public partial class SoOrder
{
    [Key]
    [Column("SO_ORDER_ID")]
    public long SoOrderId { get; set; }

    [Required]
    [Column("ORDER_NO")]
    [StringLength(20)]
    [Unicode(false)]
    public string OrderNo { get; set; }

    [Column("ORDER_DATE", TypeName = "datetime")]
    public DateTime OrderDate { get; set; }

    [Column("COM_CUSTOMER_ID")]
    public int ComCustomerId { get; set; }

    [Required]
    [Column("ADDRESS")]
    [StringLength(100)]
    [Unicode(false)]
    public string Address { get; set; }
    [NotMapped]
    public string _ComCustomerName { get; set; }
}